// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package saluto

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID          int64
	Displayname string
	Body        string
	Timeposted  pgtype.Timestamp
}
