// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package saluto

import (
	"context"
)

const getMessages = `-- name: GetMessages :many
SELECT
  id,
  displayName,
  body,
  timePosted
FROM post
ORDER BY timePosted desc
`

func (q *Queries) GetMessages(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, getMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Displayname,
			&i.Body,
			&i.Timeposted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postMessage = `-- name: PostMessage :exec
INSERT INTO post (displayName, body, timePosted)
VALUES ($1, $2, CURRENT_TIMESTAMP(2))
`

type PostMessageParams struct {
	Displayname string
	Body        string
}

func (q *Queries) PostMessage(ctx context.Context, arg PostMessageParams) error {
	_, err := q.db.Exec(ctx, postMessage, arg.Displayname, arg.Body)
	return err
}
